[package]
name = "ascii-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
jpeg-decoder = "0.3.1"
palette = "0.7.6"
termion = "4.0.2"

[profile.release]
opt-level = 3
codegen-unit = 1
debug = false
